const recipes = [
  {
    title: "Chimichurri Tempeh",
    ingredients: [
      "8  ounces tempeh, sliced through the length once, then each 1/2 piece cut into fours.",
      "4  cloves of garlic, pressed.",
      "1  cup loosely packed chopped fresh cilantro",
      "1  cup loosely packed chopped fresh parsley",
      "1  teaspoon dried oregano",
      "1/4  cup red wine vinegar",
      "2  tablespoons olive oil",
      "1/2  teaspoon red pepper flakes",
      " 1/2  teaspoon salt",
      " 3/4  cup vegetable or chicken broth",
      " 1  tablespoon tamari (or soy sauce or Bragg's amino acid liquid)",
      " vegetable oil for frying",
    ],
    instructions: [
      "Steam tempeh for 10 minutes.",
      "While it's steaming, put all the ingredients EXCEPT the tamari into a blender and blend until relatively .smooth.",
      "Pour 1/2 a cup of the chimichurri (blender content) into a measuring cup and add the tamari to make the marinade.",
      "Pour 2 tablespoons of the marinade into a plate. Place the warm tempeh on the plate and pour the 1/2 the marinade over it. Rub in the marinade on top of the tempeh. Let sit for 1/2 and hour, flip the tempeh, rub in the rest of the marinade on that side. Let sit for another 1/2 hour.",
      "Preheat a large, heavy bottom pan over medium-high heat. Cover the bottom of the pan with vegetable oil. When the oil is hot, place all the tempeh in the pan at once and cook until golden brown. Flip the tempeh (add more oil if necessary) and cook until golden brown",
      "To serve, use the remaining chimichurri (without tamari) as a sauce on top of the tempeh.",
    ],
    img: "chimichurri-tempeh.jpg",
  },
  {
    title: "Slow Cooker Butternut Squash Soup",
    ingredients: [
      "2 cups vegetable stock",
      "2 cloves garlic, peeled and minced",
      "1 carrot, peeled and diced",
      "1 Granny Smith apple, cored and diced",
      "1 medium (uncooked) butternut squash, peeled, seeded and diced",
      "1 sprig fresh sage",
      "1 white onion, diced",
      "1/2 teaspoon salt, or more to taste",
      "1/4 teaspoon freshly-ground black pepper, or more to taste",
      "1/8 teaspoon cayenne, or more to taste",
      "pinch of ground cinnamon and nutmeg",
      "1/2 cup canned (unsweetened) coconut milk",
      " optional garnishes: extra coconut milk and a sprinkle of smoked paprika (or cayenne)",
    ],
    instructions: [
      "Add vegetable stock, garlic, carrot, apple, butternut squash, sage, onion, salt, pepper, cayenne, cinnamon and nutmeg to a small (4-quart) slow cooker or large (6-quart) slow cooker. Toss to combine.",
      "Cook for 6-8 hours on low, or 3-4 hours on high, or until the squash is completely tender and mashes easily with a fork.  Remove and discard the sage.  Stir in the coconut milk.",
      "Use an immersion blender to puree the soup until smooth.  (Or you can transfer the soup in two batches into a traditional blender, and puree until smooth, being very careful when working with the hot liquid.)  Taste, and season with additional salt, pepper and cayenne if needed.",
      "Serve warm, with optional garnishes if desired.",
    ],
    img: "butternut-squash-soup.jpg",
  },
  {
    title: "Chimichurri Tempeh",
    ingredients: [
      "8 ounces (227 g) tempeh (if GF, ensure gluten-free friendly)",
      "1 fresh or dried bird's eye chili, minced/crushed (or sub 1/4 tsp red pepper flake)",
      "1 1/2 Tbsp (20 ml) sesame oil (if avoiding oil, leave this out and add a bit more lime, soy sauce, and maple syrup)",
      "2 Tbsp (32 g) salted creamy peanut (or almond, cashew, or sunbutter)",
      "2 Tbsp (30 ml) gluten-free tamari (or soy sauce if not GF)",
      "2 Tbsp (30 ml) lime juice",
      "3 Tbsp (45 ml) maple syrup",
    ],
    instructions: [
      "To remove bitterness from the tempeh, add to rimmed skillet or saucepan filled with 1 inch of water and bring to a low boil over medium heat. Steam tempeh for a total of 10-12 minutes, flipping once at the halfway point. Then rinse, pat dry, and cut into thin, bite-size pieces. I prefer slicing the tempeh in half lengthwise then cutting into small triangles. (The smaller the pieces, the better they can soak up the marinade.) Set aside.",
      "Mix marinade by adding chili, sesame oil, peanut butter, tamari, lime juice, and maple syrup. Whisk to combine. Taste and adjust flavor as needed, adding more crushed chili for heat, maple syrup for sweetness, lime juice for acidity, or tamari for saltiness. Don't be shy - you want this extremely flavorful!",
      "Add the sliced tempeh to the marinade and toss to coat. Then cover and refrigerate for at least 2 hours, preferably 24 hours. I found that 24 hours infused the most flavor! While marinating, toss/stir occasionally to ensure even coating. (Pro tip: Just before baking, drizzle with a bit more maple syrup and tamari for extra flavor. Optional but recommended!)",
      "Once marinated, preheat oven to 375 degrees F (190 C) and line a baking sheet with parchment paper. Add tempeh and reserve any leftover marinade to brush/coat the tempeh once baked.",
      "Bake for 22-30 minutes or until caramelized and deep golden brown. Remove from oven and brush/coat with any remaining marinade.",
    ],
    img: "peanut-tempeh.jpg",
  },
];

export default recipes;
